kind = "web"
previewPath = "/"
title = "CampusSlot v1.0 - PLMS"
version = "1.0.0"
id = "artifacts/campusslot"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22199

[services.development]
run = "pnpm --filter @workspace/campusslot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/campusslot", "run", "build" ]
publicDir = "artifacts/campusslot/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22199"
BASE_PATH = "/"
